import {
  ArrowLeftRight,
  Atom,
  BarChart3,
  Binary,
  BookOpen,
  Bot,
  Boxes,
  Braces,
  Brain,
  BrainCircuit,
  Briefcase,
  Bug,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  Cloud,
  Compass,
  Container,
  Crown,
  Database,
  Factory,
  FileText,
  FileType2,
  Flag,
  Flame,
  FlaskConical,
  Gauge,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  GitPullRequestArrow,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  Image,
  KeyRound,
  Layers,
  LayoutDashboard,
  Library,
  ListTodo,
  Medal,
  MessageCircle,
  MessageSquareCode,
  Mic,
  MonitorSmartphone,
  Network,
  NotebookPen,
  Rocket,
  Route,
  Search,
  Send,
  Server,
  Siren,
  Sparkles,
  Spline,
  Target,
  Terminal,
  Timer,
  Trophy,
  Webhook,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

/**
 * Icons that data-driven config (nav, categories, topics, achievements) may
 * reference by name. An explicit map keeps the bundle to the icons actually
 * used instead of importing the whole lucide catalogue.
 */
const ICONS: Record<string, LucideIcon> = {
  ArrowLeftRight,
  Atom,
  BarChart3,
  Binary,
  BookOpen,
  Bot,
  Boxes,
  Braces,
  Brain,
  BrainCircuit,
  Briefcase,
  Bug,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  Cloud,
  Compass,
  Container,
  Crown,
  Database,
  Factory,
  FileText,
  FileType2,
  Flag,
  Flame,
  FlaskConical,
  Gauge,
  GitBranch,
  GitCommitHorizontal,
  GitFork,
  GitPullRequestArrow,
  Globe,
  GraduationCap,
  Hammer,
  Heart,
  Image,
  KeyRound,
  Layers,
  LayoutDashboard,
  Library,
  ListTodo,
  Medal,
  MessageCircle,
  MessageSquareCode,
  Mic,
  MonitorSmartphone,
  Network,
  NotebookPen,
  Rocket,
  Route,
  Search,
  Send,
  Server,
  Siren,
  Sparkles,
  Spline,
  Target,
  Terminal,
  Timer,
  Trophy,
  Webhook,
  Workflow,
  Wrench,
  Zap,
};

interface DynamicIconProps extends LucideProps {
  name: string;
}

/** Renders a lucide icon from its PascalCase name; unknown names render nothing. */
export function DynamicIcon({ name, ...props }: DynamicIconProps) {
  const Icon = ICONS[name];
  if (!Icon) return null;
  return <Icon {...props} />;
}
